name: git_version
description: Replaces the '%version%' placeholder with your current git version
version: 0.2.3

homepage: https://github.com/MikeMitterer/dart-git_version
author: Mike Mitterer <office@mikemitterer.at>

environment:
  sdk: '>=1.20.1 <2.0.0'

# Add bin/showGitVersion.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  showGitVersion:

dependencies:
  build: ^0.12.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  where: ^1.1.0

dev_dependencies:
  test: any

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0

