name: git_version
description: Replaces the '%version%' placeholder with your current git version
version: 0.2.14

homepage: https://github.com/MikeMitterer/dart-git_version
author: Mike Mitterer <office@mikemitterer.at>

environment:
  sdk: ">=2.0.0 <3.0.0"

# Add bin/showGitVersion.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  showGitVersion:

dependencies:
  build: ^0.12.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0
  # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  where: ^4.0.0

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any

