name: git_version
description: Replaces the '%version%' placeholder with your current git version
version: 0.1.7

homepage: https://github.com/MikeMitterer/dart-git_version
author: Mike Mitterer <office@mikemitterer.at>

environment:
  sdk: '>=1.20.1 <2.0.0'

# Add bin/showGitVersion.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  showGitVersion:

dependencies:

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  barback: ^0.15.0
  where: ^1.1.0

dev_dependencies:
  test: ^0.12.0
